apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven' // 应用插件

group = 'com.github.454126389' // 替换为你的 GitHub 用户名
android {
    compileSdkVersion cfgs.compileSdkVersion
    buildToolsVersion cfgs.buildToolsVersion

    defaultConfig {
        minSdkVersion cfgs.minSdkVersion
        targetSdkVersion cfgs.targetSdkVersion
        versionCode 1
        versionName "1.0.0"


        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    api project(':ucrop')
    //noinspection GradleCompatible
    implementation "androidx.appcompat:appcompat:${cfgs.version_appcompat}"
    //noinspection GradleCompatible
    implementation "androidx.recyclerview:recyclerview:${cfgs.version_recyclerview}"
    implementation "androidx.concurrent:concurrent-futures:${cfgs.futures_version}"
    implementation "androidx.camera:camera-lifecycle:${cfgs.lifecycle_version}"
    api "androidx.camera:camera-core:${cfgs.camerax_version}"
    api "androidx.camera:camera-camera2:${cfgs.camerax_version}"
}
